// <auto-generated />
using System;
using EliandroProjetoManha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EliandroProjetoManha.Migrations
{
    [DbContext(typeof(EliandroProjetoManhaContext))]
    [Migration("20200705163911_SegundaMigracao")]
    partial class SegundaMigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EliandroProjetoManha.Models.Departamento", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("PedidoId");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("EliandroProjetoManha.Models.Pedido", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int?>("DepartamentoPedidoId");

                    b.Property<string>("Fornecedor");

                    b.Property<string>("Produto");

                    b.Property<int>("Quantidade");

                    b.Property<double>("Valor");

                    b.HasKey("ProdutoId");

                    b.HasIndex("DepartamentoPedidoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("EliandroProjetoManha.Models.RegistroPedidos", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Horario");

                    b.Property<int?>("PedidoProdutoId");

                    b.Property<double>("Quantia");

                    b.Property<int>("Status");

                    b.HasKey("PedidoId");

                    b.HasIndex("PedidoProdutoId");

                    b.ToTable("RegistroPedidos");
                });

            modelBuilder.Entity("EliandroProjetoManha.Models.Pedido", b =>
                {
                    b.HasOne("EliandroProjetoManha.Models.Departamento", "Departamento")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("DepartamentoPedidoId");
                });

            modelBuilder.Entity("EliandroProjetoManha.Models.RegistroPedidos", b =>
                {
                    b.HasOne("EliandroProjetoManha.Models.Pedido", "Pedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("PedidoProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
